/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GirisRouteImport } from './routes/giris'
import { Route as YetkiliRouteImport } from './routes/_yetkili'
import { Route as YetkiliIndexRouteImport } from './routes/_yetkili.index'
import { Route as YetkiliUrunListeRouteImport } from './routes/_yetkili.urun.liste'
import { Route as YetkiliCariListeRouteImport } from './routes/_yetkili.cari.liste'
import { Route as YetkiliCariCariIdRouteImport } from './routes/_yetkili.cari.$cariId'
import { Route as YetkiliAyarlarKullanicilarRouteImport } from './routes/_yetkili.ayarlar.kullanicilar'
import { Route as YetkiliAyarlarGenelRouteImport } from './routes/_yetkili.ayarlar.genel'

const GirisRoute = GirisRouteImport.update({
  id: '/giris',
  path: '/giris',
  getParentRoute: () => rootRouteImport,
} as any)
const YetkiliRoute = YetkiliRouteImport.update({
  id: '/_yetkili',
  getParentRoute: () => rootRouteImport,
} as any)
const YetkiliIndexRoute = YetkiliIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => YetkiliRoute,
} as any)
const YetkiliUrunListeRoute = YetkiliUrunListeRouteImport.update({
  id: '/urun/liste',
  path: '/urun/liste',
  getParentRoute: () => YetkiliRoute,
} as any)
const YetkiliCariListeRoute = YetkiliCariListeRouteImport.update({
  id: '/cari/liste',
  path: '/cari/liste',
  getParentRoute: () => YetkiliRoute,
} as any)
const YetkiliCariCariIdRoute = YetkiliCariCariIdRouteImport.update({
  id: '/cari/$cariId',
  path: '/cari/$cariId',
  getParentRoute: () => YetkiliRoute,
} as any)
const YetkiliAyarlarKullanicilarRoute =
  YetkiliAyarlarKullanicilarRouteImport.update({
    id: '/ayarlar/kullanicilar',
    path: '/ayarlar/kullanicilar',
    getParentRoute: () => YetkiliRoute,
  } as any)
const YetkiliAyarlarGenelRoute = YetkiliAyarlarGenelRouteImport.update({
  id: '/ayarlar/genel',
  path: '/ayarlar/genel',
  getParentRoute: () => YetkiliRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof YetkiliIndexRoute
  '/giris': typeof GirisRoute
  '/ayarlar/genel': typeof YetkiliAyarlarGenelRoute
  '/ayarlar/kullanicilar': typeof YetkiliAyarlarKullanicilarRoute
  '/cari/$cariId': typeof YetkiliCariCariIdRoute
  '/cari/liste': typeof YetkiliCariListeRoute
  '/urun/liste': typeof YetkiliUrunListeRoute
}
export interface FileRoutesByTo {
  '/giris': typeof GirisRoute
  '/': typeof YetkiliIndexRoute
  '/ayarlar/genel': typeof YetkiliAyarlarGenelRoute
  '/ayarlar/kullanicilar': typeof YetkiliAyarlarKullanicilarRoute
  '/cari/$cariId': typeof YetkiliCariCariIdRoute
  '/cari/liste': typeof YetkiliCariListeRoute
  '/urun/liste': typeof YetkiliUrunListeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_yetkili': typeof YetkiliRouteWithChildren
  '/giris': typeof GirisRoute
  '/_yetkili/': typeof YetkiliIndexRoute
  '/_yetkili/ayarlar/genel': typeof YetkiliAyarlarGenelRoute
  '/_yetkili/ayarlar/kullanicilar': typeof YetkiliAyarlarKullanicilarRoute
  '/_yetkili/cari/$cariId': typeof YetkiliCariCariIdRoute
  '/_yetkili/cari/liste': typeof YetkiliCariListeRoute
  '/_yetkili/urun/liste': typeof YetkiliUrunListeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/giris'
    | '/ayarlar/genel'
    | '/ayarlar/kullanicilar'
    | '/cari/$cariId'
    | '/cari/liste'
    | '/urun/liste'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/giris'
    | '/'
    | '/ayarlar/genel'
    | '/ayarlar/kullanicilar'
    | '/cari/$cariId'
    | '/cari/liste'
    | '/urun/liste'
  id:
    | '__root__'
    | '/_yetkili'
    | '/giris'
    | '/_yetkili/'
    | '/_yetkili/ayarlar/genel'
    | '/_yetkili/ayarlar/kullanicilar'
    | '/_yetkili/cari/$cariId'
    | '/_yetkili/cari/liste'
    | '/_yetkili/urun/liste'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  YetkiliRoute: typeof YetkiliRouteWithChildren
  GirisRoute: typeof GirisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/giris': {
      id: '/giris'
      path: '/giris'
      fullPath: '/giris'
      preLoaderRoute: typeof GirisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_yetkili': {
      id: '/_yetkili'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof YetkiliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_yetkili/': {
      id: '/_yetkili/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof YetkiliIndexRouteImport
      parentRoute: typeof YetkiliRoute
    }
    '/_yetkili/urun/liste': {
      id: '/_yetkili/urun/liste'
      path: '/urun/liste'
      fullPath: '/urun/liste'
      preLoaderRoute: typeof YetkiliUrunListeRouteImport
      parentRoute: typeof YetkiliRoute
    }
    '/_yetkili/cari/liste': {
      id: '/_yetkili/cari/liste'
      path: '/cari/liste'
      fullPath: '/cari/liste'
      preLoaderRoute: typeof YetkiliCariListeRouteImport
      parentRoute: typeof YetkiliRoute
    }
    '/_yetkili/cari/$cariId': {
      id: '/_yetkili/cari/$cariId'
      path: '/cari/$cariId'
      fullPath: '/cari/$cariId'
      preLoaderRoute: typeof YetkiliCariCariIdRouteImport
      parentRoute: typeof YetkiliRoute
    }
    '/_yetkili/ayarlar/kullanicilar': {
      id: '/_yetkili/ayarlar/kullanicilar'
      path: '/ayarlar/kullanicilar'
      fullPath: '/ayarlar/kullanicilar'
      preLoaderRoute: typeof YetkiliAyarlarKullanicilarRouteImport
      parentRoute: typeof YetkiliRoute
    }
    '/_yetkili/ayarlar/genel': {
      id: '/_yetkili/ayarlar/genel'
      path: '/ayarlar/genel'
      fullPath: '/ayarlar/genel'
      preLoaderRoute: typeof YetkiliAyarlarGenelRouteImport
      parentRoute: typeof YetkiliRoute
    }
  }
}

interface YetkiliRouteChildren {
  YetkiliIndexRoute: typeof YetkiliIndexRoute
  YetkiliAyarlarGenelRoute: typeof YetkiliAyarlarGenelRoute
  YetkiliAyarlarKullanicilarRoute: typeof YetkiliAyarlarKullanicilarRoute
  YetkiliCariCariIdRoute: typeof YetkiliCariCariIdRoute
  YetkiliCariListeRoute: typeof YetkiliCariListeRoute
  YetkiliUrunListeRoute: typeof YetkiliUrunListeRoute
}

const YetkiliRouteChildren: YetkiliRouteChildren = {
  YetkiliIndexRoute: YetkiliIndexRoute,
  YetkiliAyarlarGenelRoute: YetkiliAyarlarGenelRoute,
  YetkiliAyarlarKullanicilarRoute: YetkiliAyarlarKullanicilarRoute,
  YetkiliCariCariIdRoute: YetkiliCariCariIdRoute,
  YetkiliCariListeRoute: YetkiliCariListeRoute,
  YetkiliUrunListeRoute: YetkiliUrunListeRoute,
}

const YetkiliRouteWithChildren =
  YetkiliRoute._addFileChildren(YetkiliRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  YetkiliRoute: YetkiliRouteWithChildren,
  GirisRoute: GirisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
