/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GirisRouteImport } from './routes/giris'
import { Route as YetkiliRouteImport } from './routes/_yetkili'
import { Route as YetkiliIndexRouteImport } from './routes/_yetkili.index'
import { Route as YetkiliUrunIndexRouteImport } from './routes/_yetkili.urun.index'
import { Route as YetkiliCariIndexRouteImport } from './routes/_yetkili.cari.index'
import { Route as YetkiliAyarlarIndexRouteImport } from './routes/_yetkili.ayarlar.index'
import { Route as YetkiliCariCariIdRouteImport } from './routes/_yetkili.cari.$cariId'

const GirisRoute = GirisRouteImport.update({
  id: '/giris',
  path: '/giris',
  getParentRoute: () => rootRouteImport,
} as any)
const YetkiliRoute = YetkiliRouteImport.update({
  id: '/_yetkili',
  getParentRoute: () => rootRouteImport,
} as any)
const YetkiliIndexRoute = YetkiliIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => YetkiliRoute,
} as any)
const YetkiliUrunIndexRoute = YetkiliUrunIndexRouteImport.update({
  id: '/urun/',
  path: '/urun/',
  getParentRoute: () => YetkiliRoute,
} as any)
const YetkiliCariIndexRoute = YetkiliCariIndexRouteImport.update({
  id: '/cari/',
  path: '/cari/',
  getParentRoute: () => YetkiliRoute,
} as any)
const YetkiliAyarlarIndexRoute = YetkiliAyarlarIndexRouteImport.update({
  id: '/ayarlar/',
  path: '/ayarlar/',
  getParentRoute: () => YetkiliRoute,
} as any)
const YetkiliCariCariIdRoute = YetkiliCariCariIdRouteImport.update({
  id: '/cari/$cariId',
  path: '/cari/$cariId',
  getParentRoute: () => YetkiliRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof YetkiliIndexRoute
  '/giris': typeof GirisRoute
  '/cari/$cariId': typeof YetkiliCariCariIdRoute
  '/ayarlar/': typeof YetkiliAyarlarIndexRoute
  '/cari/': typeof YetkiliCariIndexRoute
  '/urun/': typeof YetkiliUrunIndexRoute
}
export interface FileRoutesByTo {
  '/giris': typeof GirisRoute
  '/': typeof YetkiliIndexRoute
  '/cari/$cariId': typeof YetkiliCariCariIdRoute
  '/ayarlar': typeof YetkiliAyarlarIndexRoute
  '/cari': typeof YetkiliCariIndexRoute
  '/urun': typeof YetkiliUrunIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_yetkili': typeof YetkiliRouteWithChildren
  '/giris': typeof GirisRoute
  '/_yetkili/': typeof YetkiliIndexRoute
  '/_yetkili/cari/$cariId': typeof YetkiliCariCariIdRoute
  '/_yetkili/ayarlar/': typeof YetkiliAyarlarIndexRoute
  '/_yetkili/cari/': typeof YetkiliCariIndexRoute
  '/_yetkili/urun/': typeof YetkiliUrunIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/giris'
    | '/cari/$cariId'
    | '/ayarlar/'
    | '/cari/'
    | '/urun/'
  fileRoutesByTo: FileRoutesByTo
  to: '/giris' | '/' | '/cari/$cariId' | '/ayarlar' | '/cari' | '/urun'
  id:
    | '__root__'
    | '/_yetkili'
    | '/giris'
    | '/_yetkili/'
    | '/_yetkili/cari/$cariId'
    | '/_yetkili/ayarlar/'
    | '/_yetkili/cari/'
    | '/_yetkili/urun/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  YetkiliRoute: typeof YetkiliRouteWithChildren
  GirisRoute: typeof GirisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/giris': {
      id: '/giris'
      path: '/giris'
      fullPath: '/giris'
      preLoaderRoute: typeof GirisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_yetkili': {
      id: '/_yetkili'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof YetkiliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_yetkili/': {
      id: '/_yetkili/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof YetkiliIndexRouteImport
      parentRoute: typeof YetkiliRoute
    }
    '/_yetkili/urun/': {
      id: '/_yetkili/urun/'
      path: '/urun'
      fullPath: '/urun/'
      preLoaderRoute: typeof YetkiliUrunIndexRouteImport
      parentRoute: typeof YetkiliRoute
    }
    '/_yetkili/cari/': {
      id: '/_yetkili/cari/'
      path: '/cari'
      fullPath: '/cari/'
      preLoaderRoute: typeof YetkiliCariIndexRouteImport
      parentRoute: typeof YetkiliRoute
    }
    '/_yetkili/ayarlar/': {
      id: '/_yetkili/ayarlar/'
      path: '/ayarlar'
      fullPath: '/ayarlar/'
      preLoaderRoute: typeof YetkiliAyarlarIndexRouteImport
      parentRoute: typeof YetkiliRoute
    }
    '/_yetkili/cari/$cariId': {
      id: '/_yetkili/cari/$cariId'
      path: '/cari/$cariId'
      fullPath: '/cari/$cariId'
      preLoaderRoute: typeof YetkiliCariCariIdRouteImport
      parentRoute: typeof YetkiliRoute
    }
  }
}

interface YetkiliRouteChildren {
  YetkiliIndexRoute: typeof YetkiliIndexRoute
  YetkiliCariCariIdRoute: typeof YetkiliCariCariIdRoute
  YetkiliAyarlarIndexRoute: typeof YetkiliAyarlarIndexRoute
  YetkiliCariIndexRoute: typeof YetkiliCariIndexRoute
  YetkiliUrunIndexRoute: typeof YetkiliUrunIndexRoute
}

const YetkiliRouteChildren: YetkiliRouteChildren = {
  YetkiliIndexRoute: YetkiliIndexRoute,
  YetkiliCariCariIdRoute: YetkiliCariCariIdRoute,
  YetkiliAyarlarIndexRoute: YetkiliAyarlarIndexRoute,
  YetkiliCariIndexRoute: YetkiliCariIndexRoute,
  YetkiliUrunIndexRoute: YetkiliUrunIndexRoute,
}

const YetkiliRouteWithChildren =
  YetkiliRoute._addFileChildren(YetkiliRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  YetkiliRoute: YetkiliRouteWithChildren,
  GirisRoute: GirisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
